/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      /* ── Colours ─────────────────────────────────────── */
      colors: {
        primary: {
          50:  'var(--color-primary-50)',
          100: 'var(--color-primary-100)',
          200: 'var(--color-primary-200)',
          300: 'var(--color-primary-300)',
          400: 'var(--color-primary-400)',
          500: 'var(--color-primary-500)',
          600: 'var(--color-primary-600)',
          700: 'var(--color-primary-700)',
          800: 'var(--color-primary-800)',
          900: 'var(--color-primary-900)',
          950: 'var(--color-primary-950)',
          DEFAULT: 'var(--color-primary-600)',
        },
        secondary: {
          50:  'var(--color-secondary-50)',
          100: 'var(--color-secondary-100)',
          200: 'var(--color-secondary-200)',
          300: 'var(--color-secondary-300)',
          400: 'var(--color-secondary-400)',
          500: 'var(--color-secondary-500)',
          600: 'var(--color-secondary-600)',
          700: 'var(--color-secondary-700)',
          800: 'var(--color-secondary-800)',
          900: 'var(--color-secondary-900)',
          950: 'var(--color-secondary-950)',
          DEFAULT: 'var(--color-secondary-600)',
        },
        success: {
          50:  'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
          DEFAULT: 'var(--color-success-600)',
        },
        warning: {
          50:  'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
          DEFAULT: 'var(--color-warning-500)',
        },
        danger: {
          50:  'var(--color-danger-50)',
          100: 'var(--color-danger-100)',
          200: 'var(--color-danger-200)',
          300: 'var(--color-danger-300)',
          400: 'var(--color-danger-400)',
          500: 'var(--color-danger-500)',
          600: 'var(--color-danger-600)',
          700: 'var(--color-danger-700)',
          800: 'var(--color-danger-800)',
          900: 'var(--color-danger-900)',
          DEFAULT: 'var(--color-danger-600)',
        },
        neutral: {
          50:  'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
          DEFAULT: 'var(--color-neutral-700)',
        },
        surface: {
          DEFAULT:  'var(--color-surface)',
          elevated: 'var(--color-surface-elevated)',
          overlay:  'var(--color-surface-overlay)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          strong:  'var(--color-border-strong)',
        },
        text: {
          primary:   'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          disabled:  'var(--color-text-disabled)',
          inverse:   'var(--color-text-inverse)',
          link:      'var(--color-text-link)',
        },
      },

      /* ── Spacing ──────────────────────────────────────── */
      spacing: {
        px:    'var(--spacing-px)',
        '0.5': 'var(--spacing-0-5)',
        '1':   'var(--spacing-1)',
        '1.5': 'var(--spacing-1-5)',
        '2':   'var(--spacing-2)',
        '2.5': 'var(--spacing-2-5)',
        '3':   'var(--spacing-3)',
        '3.5': 'var(--spacing-3-5)',
        '4':   'var(--spacing-4)',
        '5':   'var(--spacing-5)',
        '6':   'var(--spacing-6)',
        '7':   'var(--spacing-7)',
        '8':   'var(--spacing-8)',
        '9':   'var(--spacing-9)',
        '10':  'var(--spacing-10)',
        '11':  'var(--spacing-11)',
        '12':  'var(--spacing-12)',
        '14':  'var(--spacing-14)',
        '16':  'var(--spacing-16)',
        '20':  'var(--spacing-20)',
        '24':  'var(--spacing-24)',
        '28':  'var(--spacing-28)',
        '32':  'var(--spacing-32)',
        '36':  'var(--spacing-36)',
        '40':  'var(--spacing-40)',
        '48':  'var(--spacing-48)',
        '56':  'var(--spacing-56)',
        '64':  'var(--spacing-64)',
      },

      /* ── Border Radius ────────────────────────────────── */
      borderRadius: {
        none:  'var(--radius-none)',
        sm:    'var(--radius-sm)',
        DEFAULT:'var(--radius-base)',
        md:    'var(--radius-md)',
        lg:    'var(--radius-lg)',
        xl:    'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full:  'var(--radius-full)',
      },

      /* ── Box Shadows ──────────────────────────────────── */
      boxShadow: {
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        DEFAULT:'var(--shadow-md)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        xl:    'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        none:  'var(--shadow-none)',
      },

      /* ── Typography ───────────────────────────────────── */
      fontFamily: {
        sans: 'var(--font-family-sans)',
        mono: 'var(--font-family-mono)',
      },
      fontSize: {
        xs:   ['var(--font-size-xs)',   { lineHeight: 'var(--line-height-normal)' }],
        sm:   ['var(--font-size-sm)',   { lineHeight: 'var(--line-height-normal)' }],
        base: ['var(--font-size-base)', { lineHeight: 'var(--line-height-normal)' }],
        lg:   ['var(--font-size-lg)',   { lineHeight: 'var(--line-height-relaxed)' }],
        xl:   ['var(--font-size-xl)',   { lineHeight: 'var(--line-height-relaxed)' }],
        '2xl':['var(--font-size-2xl)', { lineHeight: 'var(--line-height-snug)' }],
        '3xl':['var(--font-size-3xl)', { lineHeight: 'var(--line-height-tight)' }],
        '4xl':['var(--font-size-4xl)', { lineHeight: 'var(--line-height-tight)' }],
        '5xl':['var(--font-size-5xl)', { lineHeight: 'var(--line-height-tight)' }],
      },
      fontWeight: {
        normal:    'var(--font-weight-normal)',
        medium:    'var(--font-weight-medium)',
        semibold:  'var(--font-weight-semibold)',
        bold:      'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
      },

      /* ── Transitions ──────────────────────────────────── */
      transitionDuration: {
        fast: '150ms',
        base: '200ms',
        slow: '300ms',
      },

      /* ── Z-index ──────────────────────────────────────── */
      zIndex: {
        base:     'var(--z-base)',
        raised:   'var(--z-raised)',
        dropdown: 'var(--z-dropdown)',
        sticky:   'var(--z-sticky)',
        fixed:    'var(--z-fixed)',
        modal:    'var(--z-modal)',
        toast:    'var(--z-toast)',
        tooltip:  'var(--z-tooltip)',
      },
    },
  },
  plugins: [],
};
